export default [
  {
    id: 1,
    title: '首页',
    icon: null,
    href: 'statistics',
    target: null,
    isShow: null,
    type: 0,
    dna: '0',
  },
  {
    id: 212,
    title: '仪表盘',
    icon: null,
    href: 'dashboard',
    target: null,
    isShow: null,
    type: 2,
    dna: '1',
  },
  {
    id: 213,
    title: '日志分析',
    icon: '',
    href: 'kibana',
    target: null,
    isShow: null,
    type: 0,
    dna: '1-0',
  },
  {
    id: 216,
    title: '链路追踪',
    icon: '',
    href: 'zipkin',
    target: null,
    isShow: null,
    type: 0,
    dna: '1-1',
  },
  {
    id: 214,
    title: '服务监控',
    icon: '',
    href: 'admin',
    target: null,
    isShow: null,
    type: 0,
    dna: '1-2',
  },

  {
    id: 10,
    title: '钥匙管理',
    icon: 'key',
    href: 'keys',
    target: null,
    isShow: null,
    type: 2,
    dna: '2',
  },
  {
    id: 11,
    title: '钥匙信息',
    icon: null,
    href: 'info',
    target: null,
    isShow: null,
    type: 0,
    dna: '2-0',
  },
  {
    id: 12,
    title: '钥匙使用日志',
    icon: null,
    href: 'logs',
    target: null,
    isShow: null,
    type: 0,
    dna: '2-1',
  },
  {
    id: 15,
    title: '车辆管理',
    icon: 'car',
    href: 'cars',
    target: null,
    isShow: null,
    type: 2,
    dna: '3',
  },
  {
    id: 16,
    title: '蓝牙信息',
    icon: null,
    href: 'bluetooth',
    target: null,
    isShow: null,
    type: 0,
    dna: '3-0',
  },
  {
    id: 17,
    title: '车辆信息',
    icon: null,
    href: 'vehicle',
    target: null,
    isShow: null,
    type: 0,
    dna: '3-1',
  },
  {
    id: 25,
    title: '用户管理',
    icon: 'user',
    href: 'customer',
    target: null,
    isShow: null,
    type: 2,
    dna: '4',
  },
  {
    id: 26,
    title: '用户信息',
    icon: null,
    href: 'info',
    target: null,
    isShow: null,
    type: 0,
    dna: '4-0',
  },
  {
    id: 27,
    title: '日志管理',
    icon: 'fileSearch',
    href: 'log',
    target: null,
    isShow: null,
    type: 2,
    dna: '5',
  },
  {
    id: 28,
    title: '使用日志',
    icon: null,
    href: 'use',
    target: null,
    isShow: null,
    type: 0,
    dna: '5-0',
  },
  {
    id: 29,
    title: '异常日志',
    icon: null,
    href: 'error',
    target: null,
    isShow: null,
    type: 0,
    dna: '5-1',
  },
  {
    id: 34,
    title: '系统管理',
    icon: 'setting',
    href: 'sys',
    target: null,
    isShow: null,
    type: 2,
    dna: '7',
  },
  {
    id: 35,
    title: '系统用户',
    icon: '',
    href: 'userManage',
    target: null,
    isShow: null,
    type: 0,
    dna: '7-0',
  },
  {
    id: 41,
    title: '角色权限管理',
    icon: '',
    href: 'userRoles',
    target: null,
    isShow: null,
    type: 0,
    dna: '7-1',
  },
  {
    id: 46,
    title: '权限资源管理',
    icon: '',
    href: 'userResource',
    target: null,
    isShow: null,
    type: 0,
    dna: '7-2',
  },
  // ,
  // {
  //   id: 36,
  //   title: '新建用户',
  //   icon: '',
  //   href: 'add',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-0-0',
  // },
  // {
  //   id: 38,
  //   title: '重置密码',
  //   icon: '',
  //   href: 'resetPwd',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-0-2',
  // },
  // {
  //   id: 177,
  //   title: '查询',
  //   icon: null,
  //   href: 'uri',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-2-0',
  // },
  // {
  //   id: 187,
  //   title: '修改密码',
  //   icon: null,
  //   href: 'uri',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-0-6',
  // },
  // {
  //   id: 44,
  //   title: '删除',
  //   icon: '',
  //   href: 'delete',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-1-2',
  // },
  // {
  //   id: 175,
  //   title: '查询',
  //   icon: null,
  //   href: 'uri',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-1-4',
  // },
  // {
  //   id: 161,
  //   title: '查询',
  //   icon: null,
  //   href: 'uri',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-3-0',
  // },
  // {
  //   id: 174,
  //   title: '查询',
  //   icon: null,
  //   href: 'uri',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-0-5',
  // },
  // {
  //   id: 179,
  //   title: '删除',
  //   icon: null,
  //   href: 'uri',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-2-2',
  // },
  // {
  //   id: 37,
  //   title: '编辑',
  //   icon: '',
  //   href: 'update',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-0-1',
  // },
  // {
  //   id: 45,
  //   title: '新建角色',
  //   icon: '',
  //   href: 'add',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-1-3',
  // },
  // {
  //   id: 43,
  //   title: '指定用户',
  //   icon: '',
  //   href: 'distribution',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-1-1',
  // },
  // {
  //   id: 180,
  //   title: '编辑',
  //   icon: null,
  //   href: 'uri',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-2-3',
  // },
  // {
  //   id: 40,
  //   title: '删除用户',
  //   icon: '',
  //   href: 'delete',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-0-4',
  // },
  // {
  //   id: 39,
  //   title: '启用/停用',
  //   icon: '',
  //   href: 'status',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-0-3',
  // },
  // {
  //   id: 178,
  //   title: '添加',
  //   icon: null,
  //   href: 'uri',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-2-1',
  // },
  // {
  //   id: 42,
  //   title: '编辑',
  //   icon: '',
  //   href: 'update',
  //   target: null,
  //   isShow: null,
  //   type: 1,
  //   dna: '7-1-0',
  // },
];
